apiVersion: apps/v1
kind: Deployment
metadata:
  name: records-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: records
  template:
    metadata:
      labels:
        app: records
    spec:
      containers:
        - name: records
          image: nobioma1/records
          env:
            - name: MONGO_DB_URI
              value: "mongodb://records-mongo-service:27017/records"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-service:4222"
            - name: NATS_CLUSTER_ID
              value: "credit"
---
apiVersion: v1
kind: Service
metadata:
  name: records-service
spec:
  selector:
    app: records
  ports:
    - name: records
      port: 5000
      targetPort: 5000
