apiVersion: apps/v1
kind: Deployment
metadata:
  name: transactions-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transactions
  template:
    metadata:
      labels:
        app: transactions
    spec:
      containers:
        - name: transactions
          image: nobioma1/transactions
          env:
            - name: MONGO_DB_URI
              value: "mongodb://transactions-mongo-service:27017/transactions"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: transactions-service
spec:
  selector:
    app: transactions
  ports:
    - name: transactions
      port: 5000
      targetPort: 5000
