name: tests-transactions

on:
  pull_request:
    paths:
      - 'transactions-service/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd transactions-service && npm install && npm run test:CI
