name: tests-users

on:
  pull_request:
    paths:
      - 'users-service/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd users-service && npm install && npm run test:CI
